/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace EAPI.CLI.Lib.DataClasses
{                   
    
    public partial class ColumnValue 
    {
        public ColumnValue()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("ColumnValue: {0}", this.Name);
        }
                            
    }
}