/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace EAPI.CLI.Lib.DataClasses
{                   
    
    public partial class CustomerType 
    {
        public CustomerType()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("CustomerType: {0}", this.Name);
        }
                            
    }
}