/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace EAPI.CLI.Lib.DataClasses
{                   
    
    /// <summary>
    /// No table description.
    /// </summary>
    public partial class ProjectVersionBuild 
    {
        public ProjectVersionBuild()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("ProjectVersionBuild: {0}", this.Name);
        }
                            
    }
}